# Generated by Django 4.2.1 on 2023-05-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaildata',
            name='receiver',
        ),
    ]
