# Generated by Django 4.2.1 on 2023-05-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0003_emaildata_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildata',
            name='read',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
