# Generated by Django 4.2.1 on 2023-05-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0004_emaildata_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaildata',
            name='read',
        ),
        migrations.RemoveField(
            model_name='emaildata',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='emaildata',
            name='subject',
        ),
        migrations.AddField(
            model_name='emaildata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
