# Generated by Django 4.2.1 on 2023-05-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0005_remove_emaildata_read_remove_emaildata_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildata',
            name='unique_code',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
